[package]
name = "letter_box"
version = "0.5.0"
authors = ["Nathan McIntosh <Nathan.McIntosh@jhuapl.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
clap = "2.33.0"
num-bigint = "0.2.6"
